// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieoqhrvblvxppwcdbvrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb3FocnZibHZ4cHB3Y2RidnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDUyODIsImV4cCI6MjA2NzI4MTI4Mn0._A5vKwcqShA4Eq7bWpiBexQ65iX420CNPdHd72KYd_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});